input:
  preproc_root: preproc
  image_ids_json: splits/uwf_labeled_smoke.json
  split_name: train

output:
  pred_dir: preds
  vis_dir: preds_vis
  exp_name: smoke_detector

model:
  checkpoint: runs/smoke_detector/checkpoints/best.pth
  backbone: resnet50_fpn
  num_classes: 21
  class_names:
    - foyer_choroidien
    - hyalite
    - membrane_epiretinenne
    - vascularite
    - hemorragie
    - oedeme_maculaire
    - nodule_choroidien
    - papille_excavee
    - granulome_choroidien
    - laser_retinien
    - macroanevrisme_arteriel
    - atrophie_peripapillaire
    - trou_opercule
    - condensations_vitre
    - exudats
    - oedeme_papillaire
    - ischemie_retine
    - nodule_cotonneux
    - anneau_weiss
    - lesion_retine

runtime:
  device: cpu
  score_thresh: 0.5
  nms_iou: 0.5
