input:
  preproc_root: preproc
  image_ids_json: splits/stage0_0.json

output:
  pred_dir: preds
  vis_dir: preds_vis
  exp_name: uveitis_ft

model:
  checkpoint: runs/uveitis_ft/checkpoints/best.pth
  backbone: retfound_vit_l
  retfound_ckpt: ""
  input_size: 768
  fpn_out_channels: 256
  freeze_blocks: 0
  num_classes: 21
  class_names:
    - foyer_choroidien
    - hyalite
    - membrane_epiretinenne
    - vascularite
    - hemorragie
    - oedeme_maculaire
    - nodule_choroidien
    - papille_excavee
    - granulome_choroidien
    - laser_retinien
    - macroanevrisme_arteriel
    - atrophie_peripapillaire
    - trou_opercule
    - condensations_vitre
    - exudats
    - oedeme_papillaire
    - ischemie_retine
    - nodule_cotonneux
    - anneau_weiss
    - lesion_retine

runtime:
  device: cuda
  score_thresh: 0.3
  nms_iou: 0.5
