input:
  manifests:
    - manifests/uwf700_uveitis100.jsonl
  split_json: splits/stage0_0.json
  class_map_yaml: configs/class_map.yaml
  preproc_root: preproc_uwf100_hr3072_masktransfer
  target_datasets:
    - uwf700
  splits:
    - train
    - val
    - test

build:
  min_component_area: 10
  min_tile_box_ratio: 0.15
  fgadr_mask_to_obb: true
  tile_require_obb_for_obb_sources: true

output:
  labels_dir: labels_coco_uwf100_hr3072_precise
  debug_dir: labels_debug_uwf100_hr3072_precise
  debug_max_images: 60
