seed: 42

run:
  output_dir: runs
  name: uwf_vitl_smoke
  tensorboard: true
  save_optimizer: false
  save_epoch_checkpoints: false

data:
  train_coco: labels_coco/uwf700_train_tiles.json
  val_coco: labels_coco/uwf700_val_tiles.json
  resize: 512

model:
  backbone: retfound_vit_l
  retfound_ckpt: models/retfound/RETFound_cfp_weights.pth
  input_size: 512
  fpn_out_channels: 256
  freeze_blocks: 22
  num_classes: 21

training:
  device: cuda
  epochs: 2
  batch_size: 2
  eval_batch_size: 2
  num_workers: 2
  lr: 0.00005
  min_lr: 0.000001
  weight_decay: 0.0001
  freeze_epochs: 1
  overfit_num_images: 16
  class_balanced_sampling: false
  eval_iou: 0.3
  fp_image_targets: [0.5, 1.0]
  amp: true
  amp_dtype: bf16

