seed: 42

run:
  output_dir: runs
  name: uveitis_from_fgadr_r50_smoke
  tensorboard: true
  save_optimizer: false
  save_epoch_checkpoints: false

data:
  train_coco: labels_coco/uwf700_train_tiles.json
  val_coco: labels_coco/uwf700_val_tiles.json
  resize: 768

model:
  detector: fasterrcnn
  backbone: resnet50_fpn
  num_classes: 21
  box_score_thresh: 0.0
  box_nms_thresh: 0.5
  box_detections_per_img: 300

training:
  device: cuda
  init_checkpoint: runs/fgadr_r50_smoke/checkpoints/best.pth
  epochs: 20
  batch_size: 2
  eval_batch_size: 2
  num_workers: 4
  lr: 0.00005
  min_lr: 0.000002
  weight_decay: 0.0001
  freeze_epochs: 0
  class_balanced_sampling: true
  eval_iou: 0.3
  eval_score_thresh: 0.05
  fp_image_targets: [0.25, 0.5, 1.0]
  amp: true
  amp_dtype: bf16

