seed: 42

run:
  output_dir: runs
  name: fgadr_vitl_unfrozen_smoke
  tensorboard: true
  save_optimizer: false
  save_epoch_checkpoints: false

data:
  train_coco: labels_coco/fgadr_train_tiles.json
  val_coco: labels_coco/fgadr_val_tiles.json
  resize: 768

model:
  detector: fasterrcnn
  backbone: retfound_vit_l
  retfound_ckpt: models/retfound/RETFound_cfp_weights.pth
  input_size: 768
  fpn_out_channels: 256
  freeze_blocks: 0
  num_classes: 21
  box_score_thresh: 0.0
  box_nms_thresh: 0.5
  box_detections_per_img: 300
  rpn_fg_iou_thresh: 0.5
  rpn_bg_iou_thresh: 0.3
  roi_fg_iou_thresh: 0.5
  roi_bg_iou_thresh: 0.5

training:
  device: cuda
  epochs: 10
  batch_size: 2
  eval_batch_size: 2
  num_workers: 4
  lr: 0.0001
  min_lr: 0.000005
  weight_decay: 0.0001
  freeze_epochs: 0
  max_train_images: 400
  max_val_images: 160
  class_balanced_sampling: false
  eval_iou: 0.3
  eval_score_thresh: 0.1
  fp_image_targets: [0.5, 1.0, 2.0]
  amp: true
  amp_dtype: bf16

