seed: 42

run:
  output_dir: runs
  name: fgadr_retinanet_r50_smoke
  tensorboard: true
  save_optimizer: false
  save_epoch_checkpoints: false

data:
  train_coco: labels_coco/fgadr_train_tiles.json
  val_coco: labels_coco/fgadr_val_tiles.json
  resize: 768

model:
  detector: retinanet
  backbone: resnet50_fpn
  num_classes: 21
  box_score_thresh: 0.05
  box_nms_thresh: 0.5
  box_detections_per_img: 300

training:
  device: cuda
  epochs: 8
  batch_size: 2
  eval_batch_size: 2
  num_workers: 4
  lr: 0.00008
  min_lr: 0.000005
  weight_decay: 0.0001
  max_train_images: 400
  max_val_images: 160
  eval_iou: 0.3
  eval_score_thresh: 0.1
  fp_image_targets: [0.5, 1.0, 2.0]
  amp: true
  amp_dtype: bf16

